config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :markets, only: [:index, :show] do
    resources :vendors, only: [:show]
  end
  get "/vendors/:id", to: "vendors#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  def index
    @markets = MarketFacade.new.get_markets
  end

  def show
    @market = MarketFacade.new.get_market(params[:id])
    @vendors = MarketFacade.new.get_market_vendors(params[:id])
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  def show
    @vendor = MarketFacade.new.get_vendor(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketMoneyFe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/markets/index.html.erb
<div style="text-align: center;">
  <h1>Markets</h1>
</div>

<table class="market-list" style="border: 1px solid black;">
  <tr>
    <th>Name</th>
    <th>City</th>
    <th>State</th>
    <th>Info</th>
  </tr>
  <% @markets.each do |market| %>
    <tr>
      <td><%= market.name %></td>
      <td><%= market.city %></td>
      <td><%= market.state %></td>
      <td>
        <%= link_to "More Info", market_path(market.id), class: "more-info-button" %>
      </td>
    </tr>
  <% end %>
</table>

app/views/markets/show.html.erb
<h1><%= @market.name %></h1>
<p><strong>Street:</strong> <%= @market.street %></p>
<p><strong>City:</strong> <%= @market.city %></p>
<p><strong>State:</strong> <%= @market.state %></p>
<p><strong>ZIP:</strong> <%= @market.zip %></p>

<h2> Vendors at our Market </h2>
<ul>
  <% @vendors.each do |vendor| %>
    <li>
    <%=link_to "#{vendor.name}", "/vendors/#{vendor.id}" %>
    </li>
  <% end %>
</ul>

app/views/vendors/show.html.erb
<div style="text-align: center;">
  <h1><%= @vendor.name %></h1>
</div>
<div style="border: 1px solid #ccc; padding: 10px; margin-top: 20px;">
  <p><strong>Contact Name:</strong> <%= @vendor.contact_name %></p>
  <p><strong>Contact Phone:</strong> <%= @vendor.contact_phone %></p>
  <p><strong>Description:</strong> <%= @vendor.description %></p>
  <p><strong>Credit:</strong> <%= @vendor.credit_accepted ? "Accepted" : "Not Accepted" %></p>
</div>